name: movie_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # A state management library that helps implement the BLoC
  bloc: ^7.1.0
  # Default icons asset for Cupertino widgets based on Apple styled icons
  cupertino_icons: ^1.0.2
  # A powerful Http client for Dart
  dio: ^4.0.0
  # Flutter package for Eva Icons
  eva_icons_flutter: ^3.0.0
  # A Dart package that helps to implement value based equality
  equatable: ^2.0.3
  # A simple yet fully customizable ratingbar for flutter
  flutter_rating_bar: ^4.0.0
  # The Font Awesome Icon pack available as Flutter Icons
  font_awesome_flutter: ^9.1.0
  # Flutter pageview indicator, easy to use
  page_indicator: ^0.4.1
  # RxDart is an implementation of the popular reactiveX api
  rxdart: ^0.27.1


dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
